### ISSUE TITLE
Load balancing with REQ and REP

### ISSUE THREAD

**Issue by dremekie** [nickdesaulniers/node-nanomsg#171]
Looking at #143  I see mention of built-in load-balancing with REQ

@reqshark mentions: `REQ/REP was designed around the need to distribute precise load balancing tasks among stateless workers`

Could you provide an example of this (perhaps in /examples)? Is a device actually needed?

Thanks much

**Comment by reqshark** [comment]
the pattern w/ automatic load balancing is `PUSH/PULL`, see #118.

`REQ/REP` provides a full manual control mechanism for constraining backpressure, since `REQ` won't fire again until the next `REP` msg. Building out your load balancing topology with `REQ/REP` seems less *builtin* to me. Here's how I see it:



🏎  **`REQ/REP`:** 5 speed manual transmission with a heavy clutch 

🚐  **`PUSH/PULL`:** luxury SUV with automatic
