### ISSUE TITLE
Build fails with MS Visual Studio 2017

### ISSUE THREAD

**Issue by rosc77** [nickdesaulniers/node-nanomsg#175]
When doing a 'npm install nanomsg', the build fails: MSBUILD : error MSB4025
Platform is Windows 10 x64.

`
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Temp\test\node_modules\nanomsg
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
`

**Comment by reqshark** [comment]
thanks for the report @rosc77, i'll take a look

**Comment by reqshark** [comment]
@rosc77 @nickdesaulniers, 

hey guys i'm taking a look at this now and verifying our build on windows, sorry it's taken so long, i'll have an update for you guys shortly

**Comment by reqshark** [comment]
@rosc77 and @nickdesaulniers, i'm glad to confirm this project still works on windows! 

BOTH latest version of master and `3.3.0` builds successfully on windows! 🚀 

It was too difficult for me to use Visual Studio 2017 alongside `node-gyp` bindings. 

Instead, make sure to setup your dev environment correctly on windows for `node-gyp` bindings like nanomsg, which can be tricky. Easiest way to do that if you already got VS2017 installed is: 

```bash
npm install --global --production windows-build-tools
```

#### make sure to run that command from an elevated PowerShell or CMD.exe (run as Administrator).

otherwise you can follow the [2nd option mentioned in the node-gyp readme](https://github.com/nodejs/node-gyp#option-2)

thanks for the report and happy holidays :)
