### ISSUE TITLE
tests/standalone/term.js is failing

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#183]
we should fix this.  I probably regressed this in https://github.com/nickdesaulniers/node-nanomsg/commit/0461f5c20cf83865d22235787e48860e760c7e39.

It's a stupid test, so not high priority.

**Comment by nickdesaulniers** [comment]
see stack trace in: https://github.com/nanomsg/nanomsg/issues/926#issuecomment-340316253

**Comment by nickdesaulniers** [comment]
I suspect we're missing a call to [uv_poll_stop.](http://docs.libuv.org/en/v1.x/fs_poll.html#c.uv_fs_poll_stop)

**Comment by nickdesaulniers** [comment]
if I remove the call to nn_term, the test completes with no aborts.  I suspect that nn_term does something to the socket the libuv doesn't like, resulting in the abort.  I bet we need to do some kind of cleanup before calling nn_abort.

**Comment by reqshark** [comment]
# nn_term  💣 

for when you want to close everything and release all related resources. Possibly it was designed to send things like libuv into chaos... check out nn_term description in the docs:

http://nanomsg.org/v1.1.0/nn_term.html

am I interpreting that intention correctly?

**Comment by reqshark** [comment]
> I suspect we're missing a call to uv_poll_stop.

totally, either that and/or `uv_close()`

because if libuv polls the nanomsg socket for fd events that drive calls to nn_recv/send...

and meanwhile `nn_term` goes and closes that `fd`, it would make sense that the next time libuv goes to poll for events, we're basically passing bogus parameters to the kernel...

there's also a node-nanomsg `pollstop()`that might work if we called it as the first order of JavaScript business before calling nn_term: https://github.com/nickdesaulniers/node-nanomsg/blob/master/src/node_nanomsg.cc#L200-L207

what do you think? I wonder if calling `uv_close()` from that `pollstop()` would also result in an error since libnanomsg might try to call `close()` on the same fd after libuv

and looking at that `pollstop()` again now another thought crosses my mind: whether an `nn_term` call at a certain point could trigger the `else` branch commented in our `pollstop()`

**Comment by nickdesaulniers** [comment]
re ipv6: https://docs.travis-ci.com/user/reference/precise/#Networking

> The virtual machines in the Legacy environment running the tests have IPv6 enabled. They do not have any external IPv4 address but are fully able to communicate with any external IPv4 service. The container-based, OS X, and GCE (both Precise and Trusty) builds do not currently have IPv6 connectivity.

Maybe we need to upgrade to trusty? https://docs.travis-ci.com/user/reference/trusty/#Using-Trusty

see also https://github.com/travis-ci/travis-ci/issues/3302
