### ISSUE TITLE
streams2 api?

### ISSUE THREAD

**Issue by jandre** [nickdesaulniers/node-nanomsg#29]
Hi,

Have you thought about a streams api for nanomsg?   

I'd like to be able to implement nanomsg with some sort of backpressure support if my downstream node stuff, for example, is too busy to actually process PULL messages coming up from my nanomsg pipeline.   The EventEmitter callback-style isn't *really* ideal since I assume it will just keep accepting messages as long as I'm still listening and has the potential to just queue up callbacks in memory, if, say, I'm inserting messages into the db on the backend and the db insert can't keep up.

I'm looking at implementing one myself if you haven't thought about it already, or if you have and have any pointers or thoughts, would love to hear them!

Best,
Jen

**Comment by reqshark** [comment]
a wonderful idea and we ought to wholesale replace EventEmitter with the `Duplex` base class.

just get rid [the call to `emit('message')`](https://github.com/reqshark/node-nanomsg/blob/streams/lib/index.js#L149)

the API change would be like `.on('data', callback)` instead of `.on('message', callback)`

`data` is a few characters shorter than `message` so it seems easier. plus you get a node stream.

keep the call to send the same, no need for any `write()` method, yet all sender type sockets could be piped to from any source. by adding a `_write()` method on the prototype, the `Duplex` base class takes care of handing the writing for us, check it out:

https://github.com/reqshark/node-nanomsg/commit/9ea49b3864a5e0f877055bd7bbb83aeb0c00c23d

what do people think?
