### ISSUE TITLE
getting double message callback on BUS socket

### ISSUE THREAD

**Issue by mango009** [nickdesaulniers/node-nanomsg#38]
Do not know if this is the problem of my code or not but I seems to be getting double messages every time I call a send on a BUS socket:

var nano = require('nanomsg'),
	argv = require('yargs').argv;

var bus = nano.socket('bus');

var addr = 'ipc:///tmp/' + argv.node;
var p1 = 'ipc:///tmp/' + argv.p1;
var p2 = 'ipc:///tmp/' + argv.p2;

console.log('binding to', addr);
bus.bind(addr);

console.log('connecting to', p1);
bus.connect(p1);
//console.log('connecting to', p2);
//bus.connect(p2);

bus.on('message', function (buf) {
    console.log(buf.toString());
});

var seq = 0;
setInterval(function () {
	seq++;
	console.log('sending...', seq);
    bus.send(argv.node + " " + seq);
}, 5000);

////////////////////////
node nano-test.js --node n0 --p1 n1
node nano-test.js --node n1 --p1 n0 

///////////////////////
n1 2
n1 2
sending... 1
n1 3
n1 3
sending... 2
n1 4
n1 4
sending... 3
n1 5
n1 5

**Comment by nickdesaulniers** [comment]
indeed, if I run the test case:

```javascript
var nano = require('./lib/index.js');
var argv = process.argv;

var bus = nano.socket('bus');

var addr = 'ipc:///tmp/' + argv[2];
var p1 = 'ipc:///tmp/' + argv[3];
var p2 = 'ipc:///tmp/' + argv[3];

console.log('binding to', addr);
bus.bind(addr);

console.log('connecting to', p1);
bus.connect(p1);

bus.on('message', function (buf) {
  console.log('received message');
  console.log(buf.toString());
});

var seq = 0;
setInterval(function () {
  seq++;
  console.log('sending...', seq);
  bus.send(argv[2] + " " + seq);
}, 5000);
```
`node test.js n0 n1` and `node test.js n1 n0` I do receive the message twice!  We will have to figure out if we're sending twice, or firing onmessage twice.

**Comment by nickdesaulniers** [comment]
Looks more like a [double receive](https://github.com/nickdesaulniers/node-nanomsg/blob/6df49d2d8f28715bf8877c894a470557ea80a067/lib/index.js#L149-L152) than double send.  Still digging.

**Comment by nickdesaulniers** [comment]
We only set the callback to lib uv once, but it seems to be firing twice, with the same callback. https://github.com/nickdesaulniers/node-nanomsg/blob/7538bfe18202d1631ba2e378e33bdd370d5203c0/src/node_nanomsg.cc#L380

**Comment by nickdesaulniers** [comment]
I think this is an extension of #10 and #11.  With bus, you should only have one process bind, and the rest connect, and they can still send each other messages.  When each process binds and connects, then this problem arises.  We can't differentiate the socket being marked readable twice from this vs receiving two different messages.  A bus socket can send and receive by simply calling bind or receive.  You don't relink them twice.  For instance, socketA and socketB only share one bind/connect on an address; what you're doing is creating two bind/connect pairs, which is messing everything up (and by #10 and #11 we don't error out at the calls to bind).

For example:

```javascript
var nano = require('../');
var bus1 = nano.socket('bus');
var bus2 = nano.socket('bus');

var addr1 = 'tcp://127.0.0.1:3000'
var addr2 = 'tcp://127.0.0.1:4000'

// Try commenting these in and rerunning for some fun!
//bus1.bind(addr1);
bus2.bind(addr2);

bus1.connect(addr2);
//bus2.connect(addr1);

bus1.on('message', function (buf) {
  console.log('received message');
  bus1.send('hello');
});

bus2.on('message', function (buf) {
  console.log('hey, I can receive without binding');
});

bus2.send('o hai');
```

**Comment by nickdesaulniers** [comment]
So in a sense, we're working correctly; we call our onmessage callback twice, since a call to send on a BUS socket that is both bound and connected to another BUS socket is technically notifying the receiver on two addresses.  For a BUS socket, the binder and the connector are irrelevant, and each pair should ever be bound/connected via one address, otherwise you can expect onmessage to be invoked once for each address they share.

**Comment by Mikke** [comment]
Hello Nick! For the first i want to say thank you for your library! However, i have a two issues to talk about, the first its according to this conversation, i'm sure that implementation of "bus" pattern is not correct, and its shouldn't fired up same event twice in that and any other case, because its one of "original" tasks for message queue service. (http://tim.dysinger.net/posts/2013-09-16-getting-started-with-nanomsg.html - last case show how it should be works). I want to help fix that, but its bring us to next issue. You library have a C++ abstraction binding inside and js interface have bindings to it - what the reason for this? May be it can be easy with binding to original (on pure C) library?

**Comment by Mikke** [comment]
https://github.com/nickdesaulniers/node-nanomsg/issues/38#event-279054299 - at this example missed sockets topology

**Comment by reqshark** [comment]
> i'm sure that implementation of "bus" pattern is not correct

bus is implemented correctly. scroll to the bottom of the getting started link you reference to see dups

> a C++ abstraction binding inside and js interface have binding to it - what the reason for this method? May be it can be easy with binding to original (on pure C) library?

we do native abstraction this way to switch data back and forth between v8 and JS runtimes.

**Comment by nickdesaulniers** [comment]
> I want to help fix that

Cool, if you spot something wrong, we're always happy to review patches.

> what the reason for this method?

v8 does not expose a C API.  nanomsg and v8 can only be tied together through C++ (or [maybe now Rust](http://calculist.org/blog/2015/12/23/neon-node-rust/)) since v8's functions which we NEED for converting JS types to C types have C++ linkage and a C++ ABI.

**Comment by reqshark** [comment]
yea it'd be nice if we didnt have to use C++.

You know... in addition to Rust, we could've also used https://github.com/node-ffi/node-ffi, but early on when i just started running some experiments and tests on [a similar binding for iojs](https://github.com/reqshark/nanomsg.iojs) and trying find the best way to write this, I ran a series of performance tests with node-ffi and found that each call carried a higher overhead than calls made with [NAN](https://github.com/nodejs/nan)... so that's i went with NAN at the time. Also that was about a year ago so maybe things are different now.
