### ISSUE TITLE
remove cpp macros

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#84]
Let's get rid of macros.  While they shorten the amount of code needed to type, they make me feel uncomfortable.

**Comment by reqshark** [comment]
sounds good to me!

being explicit where things get kinda complicated is a probably virtue.

**Comment by reqshark** [comment]
weird no auto-close? 

i wonder did the colon in the commit line prevent auto-close?

**Comment by reqshark** [comment]
Eureka!  :tophat:

I think this issue didn't auto-close for me because I took a shortcut this time, doing PR/Issue ref from commit only during the last phase of:
```bash
git rebase -i [whatever]
```
... like after you squash it lets you rename the commit message. 

I think I was probably supposed to do that PR/Issue naming ceremony one step later in:
```bash
git commit --amend
```
