### ISSUE TITLE
Behavior of PUSH PULL

### ISSUE THREAD

**Issue by thelinuxlich** [nickdesaulniers/node-nanomsg#96]
REQREP - when there are no consumers and the producer sent messages, if a consumer connects, it will receive each message slowly, per reconnecting configuration

PUSHPULL - when there are no consumers and the producer sent messages, if a consumer connects, it will receive all pending messages instantly

Is this behavior normal? Also, I see that if I leave the producer enabled for hours and a consumer connects, it will still get all those messages instantly. What's the limit?

**Comment by nickdesaulniers** [comment]
I'm not familiar enough with nanomsg to know the answer to this.  We should write a test case in C and see if we differ from the host implementation.

**Comment by reqshark** [comment]
<strong>PUSHPULL</strong>: yes this is normal behavior and how it's supposed to work without a built-in limit.

<strong>REQREP</strong>: to nail this down I think we need to talk about each side in terms of whether it's a REQ or a REP instead of the Producer/Consumer paradigm (easier for me at least). A REP will never fire without a REQ. Another subsequent REQ msg will never get ack'd until the prior REQ was recv'd/sent by the REP.

**Comment by ColorfullyMe** [comment]
@reqshark I dig into what to use PUSHPULL or REQREP for monitoring app via TCP and did land here. Please, clarify for me, if you have time as I see you are "inside things":

PULL should/will stack pending messages but PUSH blocks if it can not send the message. Looks to me as the same lock as in REQREP from pusher's point of view.

`nanocat --pull --bind tcp://*:8787 -A`
in some other terminal...
`nanocat --push --connect tcp://0.0.0.0:8787 --data HelloWorld -i 1`

works well until I Ctrl+C the first. Then I do wait ~10sec (I count) after that restart the 1st. What I got is just one single `HelloWorld` not ~10. Then all continue from begin...

So:
1. Is this the expected behavior?
2. Do node-nanomsg behave the same as nanocat in such situation?
3. To ensure msg delivery to server what is the better chose  PUSHPULL or REQREP?

Thanks!

**Comment by reqshark** [comment]
1. yes
2. yes, it should.
3. reqrep is designed more for 1-to-1 endpoints. pushpull is more like 1-to-many.

reqrep operates like two PAIR sockets but with added delivery constraints around message acknowledgement.

with pushpull you can use a single push socket and distribute the messages like a load-balancer evenly across many connected pull sockets. the more pull sockets you add, the more you can reduce message processing constraints applied to each individual pull socket endpoint. I've noticed that a single message is frequently lost when I disconnect all pull sockets and reconnect.

personally when I want to send msgs out to different endpoints I use the pub/sub pattern. When using TCP transport, there's already an underlying ACK delivery algorithm operating at a lower network layer under the hood. Message loss using PUB/SUB is a deliberate design feature: when you are publishing without a subscriber connected/bound, of course the subscriber socket is going to lose all of those messages. Otherwise, when they are connected/bound, I find pubsub more efficient than the alternatives and just as reliable.

**Comment by ColorfullyMe** [comment]
Thanks!

**Comment by reqshark** [comment]
np :)

**Comment by liukun** [comment]
I really need a limit to PUSH, then wait PULL consume some before PUSH more.

After examine, I think check the underlying `Socket.queue` length is a workaround. 

```javascript
import * as nanomsg from "nanomsg"
{
  let soc = nanomsg.socket("push")
  soc.bind("tcp://127.0.0.1:44445")
  setInterval(() => {
    if (proc.term) { // if process terminated
      if (soc) {
        soc.close()
        soc = undefined
      }
      return
    }
    if (!soc || soc.queue.length > 5) {
      return // queued enough messages, wait PULL
    }
    let now = Math.floor(Date.now() / 1000)
    soc.send("nano" + now)
    console.log("nano" + now)
  }, 1000).unref()
}
```
